### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: msg.replace is not a function

### ISSUE THREAD

**Issue by kyrylkov** [addyosmani/critical#252]
Getting this error after upgrade from 0.9.1 to 1.0.0 using Node.js 9.0.0 / Win 10 x64

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: msg.replace is not a function
```

**Comment by djbuch** [comment]
I found this : https://github.com/pocketjoso/penthouse/pull/197

**Comment by bezoerb** [comment]
Awesome job @djbuch :) 
I got the same error today and was just about to raise an issue over at penthouse.
Thanks :)

**Comment by XhmikosR** [comment]
I believe this can be closed now @bezoerb

**Comment by bezoerb** [comment]
Closing this as it's fixed in `penthouse`
